# Broadcasting means the ability of numpy to deal with the different types of arrays during the arithmetic operations

In [1]:
import numpy as np

### Broadcasting is easy if the arrays are the same like this

In [2]:
a=np.array([1,2,3,4])

In [3]:
b=np.array([11,22,33,44])

In [4]:
c=a*b

In [5]:
print(c)

[ 11  44  99 176]


In [6]:
a2=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0]])

In [7]:
print(a2)

[[ 0.  0.  0.]
 [10. 10. 10.]]


In [8]:
b2=np.array([[1.0,2.0,3.0]])

In [9]:
print(b2)

[[1. 2. 3.]]


In [10]:
print('First array')

First array


In [19]:
print(a2)

[[ 0.  0.  0.]
 [10. 10. 10.]]


In [12]:
print('\n')

In [13]:
print('Second array')

Second array


In [18]:
print(b2)

[[1. 2. 3.]]


In [15]:
print("\n")

In [16]:
print('First array + Second array')

First array + Second array


In [17]:
print(a2 +b2)

[[ 1.  2.  3.]
 [11. 12. 13.]]


### Iterating over Array

##### There is iterator object in numpy numpy.nditer


In [21]:
a3=np.arange(0,60,5)

In [40]:
print(a3)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [34]:
a3=a3.reshape(3,4)

In [35]:
print('Original array is:')

Original array is:


In [36]:
print(a3)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [37]:
print('\n')

In [38]:
print('Modifed array is:')

Modifed array is:


In [39]:
for x in np.nditer(a3):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [41]:
print('Transpoe of the original array is:')

Transpoe of the original array is:


In [45]:
print(a3)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [43]:
b3=a3.T

In [44]:
print(b3)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [46]:
for x in np.nditer(b3):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


### Iteration Order

##### If we use the F-style order then iterater use the most effective way to 

In [47]:
print('Sorted in C-style order')

Sorted in C-style order


In [52]:
c3=b3.copy(order='c')

In [53]:
print(c3)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [54]:
print('Sorted F-style order')

Sorted F-style order


In [56]:
d3=b3.copy(order='F')

In [57]:
print(d3)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


#### To use the specific type order we can use nditer

In [58]:
print("Sorted in C-style order:")

Sorted in C-style order:


In [59]:
for x in np.nditer(a,order='C'):
    print(x)

1
2
3
4


In [60]:
print('\n')

In [61]:
print("Sorted in F-style order")

Sorted in F-style order


In [63]:
for x in np.nditer(a,order='F'):
    print(x)

1
2
3
4


 ### Modifying Array Values

##### There is another optional prameter of nditer which is op_flags. It's by default value is read-only but we can set it to read -write or write-only.By using this method we can modify the array element.

In [69]:
a4=np.arange(0,60,5)

In [71]:
a4=a4.reshape(3,4)

In [64]:
print("Original array is ")

Original array is 


In [72]:
print(a4)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [74]:
# Modified array is 
for x in np.nditer(a4,op_flags=['readwrite']):
    x[...]=2*x

In [75]:
print('Modified array is ')

Modified array is 


In [76]:
print(a4)

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


#### External Loop

#### nditer class constructor has flags prameter

In [78]:
for x in np.nditer(a4,flags=['external_loop'],order='F'):
    print(x)

[ 0 40 80]
[10 50 90]
[ 20  60 100]
[ 30  70 110]


### Broadcasting Iteration

In [80]:
a=np.arange(0,60,5)

In [81]:
a=a.reshape(3,4)

In [82]:
print('Frint array is:')

Frint array is:


In [83]:
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [84]:
print('\n')

In [85]:
print('Second array is:')

Second array is:


In [86]:
b=np.array([1,2,3,4],dtype=int)

In [87]:
print(b)

[1 2 3 4]


In [88]:
print('\n')

In [89]:
print('Modified array is:')

Modified array is:


In [90]:
for x,y in np.nditer([a,b]):
    print("%d:%d"%(x,y))

0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4
