In [2]:
import numpy as np

In [3]:
x=np.array([[1,2],[3,4],[5,6]])

In [4]:
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
y=x[[0,1,2],[0,1,0]]

In [6]:
print(y)

[1 4 5]


In [17]:
x=np.array([1,2,3,4])

In [18]:
print(x)

[1 2 3 4]


In [21]:
y=x[[1,3,1,1]]

In [22]:
print(y)

[2 4 2 2]


In [23]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [24]:
print('Our array is:')

Our array is:


In [25]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
print('\n')

In [38]:
rows=np.array([[0,0],[3,3]])

In [41]:
cols=np.array([[0,2],[0,2]])

In [51]:
y=x[rows,cols]

In [50]:
print(y)

[[[ 0  1  2]
  [ 0  1  2]]

 [[ 9 10 11]
  [ 9 10 11]]]


In [52]:
print(y)

[[ 0  2]
 [ 9 11]]


In [53]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [54]:
print('Our array is:')

Our array is:


In [55]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
print('\n')

In [57]:
# Slicing

In [58]:
z=x[1:4,1:3]

In [59]:
z

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [64]:
print('Slicing using advanced index for column:')

Slicing using advanced index for column:


In [62]:
y=x[1:3,[1,2]]

In [63]:
print(y)

[[4 5]
 [7 8]]


In [65]:
print('Boolean indexing ')

Boolean indexing 


In [66]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [68]:
print(x[x>7])

[ 8  9 10 11]


In [69]:
a=np.array([np.nan,1,2,np.nan,3,4,5])

In [72]:
# To check is there any nan value
print(np.isnan(a))

[ True False False  True False False False]


In [74]:
# To remove nan value by values 
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [75]:
b=np.array([1,2+6J,5,3.5+5J])

In [76]:
print(a[np.iscomplex(a)])

[]
