### Mathematical Functions

In [1]:
import numpy as np

In [2]:
a=np.array([0,30,45,60,90])

In [3]:
print('Sine of different angles')

Sine of different angles


## Convert to radians by multiplying with pi/180

In [5]:
print(np.sin(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [6]:
print('Conine values for angles in array:')

Conine values for angles in array:


In [8]:
print(np.cos(a*np.pi/180))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [9]:
print('Tangent values for given angles:')

Tangent values for given angles:


In [10]:
print(np.tan(a*np.pi/180))

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [11]:
a=np.array([0,30,45,60,90])

In [12]:
print('Array containing sine values:')

Array containing sine values:


In [13]:
sin =np.sin(a*np.pi/180)

In [14]:
print(sin)

[0.         0.5        0.70710678 0.8660254  1.        ]


In [15]:
print('\n')

In [16]:
print('Compute sine inverse of angles. Returned values are in radians.')

Compute sine inverse of angles. Returned values are in radians.


In [17]:
inv=np.arcsin(sin)

In [18]:
print(inv)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [19]:
print('\n')

In [20]:
print('Check result by converting to degrees:')

Check result by converting to degrees:


In [21]:
print(np.degrees(inv))

[ 0. 30. 45. 60. 90.]


In [22]:
print('\n')

In [25]:
print('arccos and arctan functions behave similarly:')

arccos and arctan functions behave similarly:


In [26]:
cos =np.cos(a*np.pi/180)

In [27]:
print(cos)

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [28]:
print('\n')

In [29]:
print('Inverse of cos:')

Inverse of cos:


In [30]:
inv = np.arccos(cos)

In [31]:
print(inv)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [32]:
print('\n')

In [33]:
print('In degrees')

In degrees


In [34]:
print(np.degrees(inv))

[ 0. 30. 45. 60. 90.]


In [36]:
print('\n')

In [37]:
print('Tan function:')

Tan function:


In [38]:
tan =np.tan(a*np.pi/180)

In [39]:
print(tan)

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [40]:
print('\n')

In [41]:
print('Inverse of tan:')

Inverse of tan:


In [42]:
inv = np.arctan(tan)

In [43]:
print(inv)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [44]:
print('\n')

In [45]:
print('In degrees:')

In degrees:


In [46]:
# Array containing sine values:¶

print(np.degrees(inv))

[ 0. 30. 45. 60. 90.]


### Functions for Rounding

In [47]:
a= np.array([1.0,5.55, 123, 0.567,25.532])

In [48]:
print('Original array:')

Original array:


In [49]:
print(a)

[  1.      5.55  123.      0.567  25.532]


In [50]:
print('\n')

In [51]:
print('After rounding:')

After rounding:


In [52]:
print(np.around(a))

[  1.   6. 123.   1.  26.]


In [53]:
print(np.around(a,decimals=1))

[  1.    5.6 123.    0.6  25.5]


In [54]:
print(np.around(a,decimals=-1))

[  0.  10. 120.   0.  30.]


### numpu.floor

In [55]:
a=np.array([-1.7,1.5,-0.2,0.6,10])

In [57]:
print('The given array:')

The given array:


In [58]:
print(a)

[-1.7  1.5 -0.2  0.6 10. ]


In [59]:
print('\n')

In [60]:
print('The modified array')

The modified array


In [61]:
print(np.floor(a))

[-2.  1. -1.  0. 10.]


### numpy.ceil

In [62]:
a=np.array([-1.7,1.5,-0.2,0.6,10])

In [63]:
print('The given array:')

The given array:


In [64]:
print(a)

[-1.7  1.5 -0.2  0.6 10. ]


In [65]:
print('\n')

In [66]:
print('The modified array')

The modified array


In [67]:
print(np.ceil(a))

[-1.  2. -0.  1. 10.]
