### Matrix Library

In [1]:
import numpy as np

In [3]:
import numpy.matlib

In [4]:
print(np.matlib.empty((2,2)))

[[2.12199579e-314 6.81160649e-312]
 [1.85768683e-321 3.79442416e-321]]


In [5]:
print(np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [7]:
print(np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [9]:
numpy.matlib.eye(n=3,M=4,k=0,dtype=float)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [10]:
print(np.matlib.identity(5,dtype=float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
print(np.matlib.rand(3,3))

[[0.7682393  0.75339824 0.91184219]
 [0.14298313 0.2145262  0.90352277]
 [0.31183566 0.90070107 0.66850501]]


In [12]:
i=np.matrix('1,2;3,4')

In [13]:
print(i)

[[1 2]
 [3 4]]


In [14]:
k=np.asmatrix

In [15]:
print(k)

<function asmatrix at 0x000001416DDD1900>
