# Statistical Function

In [1]:
import numpy as np

In [2]:
a=np.array([[3,7,5],[8,4,3],[2,4,9]])

In [3]:
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [4]:
print(np.amin(a,1))

[3 3 2]


In [6]:
print(np.amin(a,0))

[2 4 3]


In [7]:
print(np.amax(a))

9


In [8]:
print(np.amax(a,axis=0))

[8 7 9]


In [9]:
print(np.amax(a,axis=1))

[7 8 9]


### numpy.ptp

In [10]:
print(np.ptp(a))

7


In [11]:
print(np.ptp(a,axis=1))

[4 5 7]


In [12]:
print(np.ptp(a,axis=0))

[6 3 6]


### numpy.percentile()

In [13]:
print(np.percentile(a,50))

4.0


In [14]:
print(np.percentile(a,50,axis=1))

[5. 4. 4.]


In [15]:
print(np.percentile(a,50,axis=0))

[3. 4. 5.]


### numpy.median()

In [16]:
print(np.median(a))

4.0


In [17]:
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [18]:
print(np.median(a,axis=0))

[3. 4. 5.]


In [19]:
print(np.median(a,axis=1))

[5. 4. 4.]


### mumpy.mean

In [20]:
print(np.mean(a))

5.0


In [21]:
print(np.mean(a,axis=0))

[4.33333333 5.         5.66666667]


In [22]:
print(np.mean(a,axis=1))

[5. 5. 5.]


### numpy.average()

In [24]:
print(np.average(a))

5.0


In [25]:
print(np.average(a,axis=0))

[4.33333333 5.         5.66666667]


In [26]:
print(np.average(a,axis=1))

[5. 5. 5.]


### Standard Deviation

In [27]:
print(np.std([1,2,3,4]))

1.118033988749895


### Variance

In [28]:
print(np.var([1,2,3,4]))

1.25
