In [1]:
import numpy as np

In [11]:
myarr= np.array([[1,2,3,4,5]])

In [3]:
myarr

array([1, 2, 3, 4, 5])

In [5]:
type(myarr)

numpy.ndarray

In [12]:
myarr.shape


(1, 5)

In [13]:
myarr.dtype

dtype('int32')

In [20]:
myarr.size

5

In [16]:
# Giving dtype of array 
myarr2=np.array([[232,545,232]], np.int8)

In [17]:
myarr2

array([[-24,  33, -24]], dtype=int8)

In [18]:
myarr2.shape

(1, 3)

In [19]:
myarr2.dtype

dtype('int8')

In [21]:
myarr2.size

3

# Array Creation: conversation from other pyton structure


In [24]:
listArray= np.array([[1,2,3],[5,8,5],[0,3,1]])

In [25]:
listArray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [26]:
listArray.dtype

dtype('int32')

In [27]:
listArray.shape

(3, 3)

In [28]:
listArray.size

9

In [31]:
np.array({12,45,21})

array({45, 12, 21}, dtype=object)

In [33]:
# To create zeros table


In [34]:
zeros= np.zeros((2,5))

In [35]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
# To create table with range

In [44]:
rng= np.arange(15)

In [45]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
rng.size

15

In [47]:
rng.shape

(15,)

In [52]:
lspace= np.linspace(1,3,3)

In [53]:
lspace

array([1., 2., 3.])

In [51]:
lspace.shape

(12,)

In [54]:
emp_like = np.empty_like(lspace)

In [55]:
emp_like

array([1., 2., 3.])

In [56]:
ide=np.identity(45)

In [57]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [58]:
ide.shape

(45, 45)

In [60]:
arr=np.arange(99)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [65]:
arr=arr.reshape(3,33)

In [66]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [71]:
# To change the shape of arr
arr=arr.ravel()
# Now its become the 1d array

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [73]:
arr.shape

(99,)

In [74]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [75]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [76]:
ar=np.array(x)

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
ar.sum(axis=0)

array([12, 15, 18])

In [79]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [81]:
# to transpos the matrix use capital T
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [83]:
# To check the number of dimensions
ar.ndim

2

In [85]:
ar.nbytes

36

In [86]:
one= np.array([1,2,3,43634,2231,56876568])

In [87]:
# To get the number of index where maximun number is
one.argmax()

5

In [88]:
one.argmin()

0

In [89]:
# It will give suggestion of element if it is sorted
one.argsort()

array([0, 1, 2, 4, 3, 5], dtype=int64)

In [90]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
# First it straten the matrix then it will index
ar.argmax()

8

In [93]:
ar.argmin()

0

In [94]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [96]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [97]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [99]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [101]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [102]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [104]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
ar2 = np.array([[1,2,1],[4,0,6],[15,2,0]])

In [106]:
ar2

array([[ 1,  2,  1],
       [ 4,  0,  6],
       [15,  2,  0]])

In [107]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [22, 10,  9]])

In [108]:
[333,121] + [121,232]

[333, 121, 121, 232]

In [109]:
ar*ar2

array([[  1,   4,   3],
       [ 16,   0,  36],
       [105,  16,   0]])

In [110]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [111]:
ar.sum()

45

In [112]:
ar.max()

9

In [113]:
ar.min()

1

In [114]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [116]:
np.count_nonzero(ar)

9

In [117]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [118]:
# To create a list of numpy array
ar.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]